<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>predictive risk</name>
  <uuid>cb4f19df-a108-4485-9870-9454de15136b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the ML scoreboard computed from
Client Information being Client ,
Industry being Industry ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
