<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>service score</name>
  <uuid>fd6502a5-ccda-4e17-92e9-5992a5930918</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the number of elements in the Services requested is more than 3
then
	add 1 to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
