<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-rule</name>
  <uuid>83d9ca3f-12ce-4079-a679-8030b003989e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML model output where
		the confidence is 0 , 
		the weight is 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
